FROM {{ base_image_name }}

ARG VENDOR=oracle
ARG PRODUCT={{ product }}
ARG PRODUCT_VERSION={{ version }}
ARG TEMP_DIR_ROOT=/tmp/${VENDOR}-${PRODUCT}
ARG TEMP_DIR=/${TEMP_DIR_ROOT}/${PRODUCT_VERSION}
ARG INSTALL_DIR_ROOT=/usr/java
ARG INSTALL_DIR=${INSTALL_DIR_ROOT}/jre1.{{ version_info['major'] }}.0_{{ version_info['minor'] }}
ARG ORACLE_USERNAME
ARG ORACLE_PASSWORD

{%- if files['linux-x64']['rpm'] %}
ARG JRE_INSTALL_RPM_URL={{ files['linux-x64']['rpm']['url'] }}
ARG JRE_INSTALL_RPM={{ files['linux-x64']['rpm']['filename'] }}
{% elif files['linux-x64']['tar.gz'] %}
ARG JRE_INSTALL_TAR_GZ_URL={{ files['linux-x64']['tar.gz']['url'] }}
ARG JRE_INSTALL_TAR_GZ={{ files['linux-x64']['tar.gz']['filename'] }}
{% elif files['linux-x64']['-rpm.bin'] %}
ARG JRE_INSTALL_RPM_BIN_URL={{ files['linux-x64']['-rpm.bin']['url'] }}
ARG JRE_INSTALL_RPM_BIN={{ files['linux-x64']['-rpm.bin']['filename'] }}
{% elif files['linux-x64']['bin'] %}
ARG JRE_INSTALL_BIN_URL={{ files['linux-x64']['bin']['url'] }}
ARG JRE_INSTALL_BIN={{ files['linux-x64']['bin']['filename'] }}
{%- endif %}
ARG JCE_POLICY_ZIP_URL={{ jce['zip']['url'] }}
ARG JCE_POLICY_ZIP={{ jce['zip']['filename'] }}

USER ${ROOT_UID}

COPY downloader.py java-import-ca-cert ${TEMP_DIR}/

RUN \
yum-install unzip python-requests && \
mkdir -p ${TEMP_DIR} && \
pushd ${TEMP_DIR} && \
cp java-import-ca-cert /usr/local/bin/ && \
chmod a+xs /usr/local/bin/java-import-ca-cert && \
{%- if files['linux-x64']['rpm'] %}
python2 downloader.py \
--url ${JRE_INSTALL_RPM_URL} \
--filename ${JRE_INSTALL_RPM} \
--username ${ORACLE_USERNAME} \
--password ${ORACLE_PASSWORD} && \
yum-install ${TEMP_DIR}/${JRE_INSTALL_RPM} && \
{% elif files['linux-x64']['-rpm.bin'] %}
python2 downloader.py \
--url ${JRE_INSTALL_RPM_BIN_URL} \
--filename ${JRE_INSTALL_RPM_BIN} \
--username ${ORACLE_USERNAME} \
--password ${ORACLE_PASSWORD} && \
chmod +x ${JRE_INSTALL_RPM_BIN} && \
./${JRE_INSTALL_RPM_BIN} && \
{% elif files['linux-x64']['bin'] %}
python2 downloader.py \
--url ${JRE_INSTALL_BIN_URL} \
--filename ${JRE_INSTALL_BIN} \
--username ${ORACLE_USERNAME} \
--password ${ORACLE_PASSWORD} && \
mkdir -p ${INSTALL_DIR_ROOT} && \
mv ${JRE_INSTALL_BIN} ${INSTALL_DIR_ROOT}/ && \
pushd ${INSTALL_DIR_ROOT} && \
chmod +x ${JRE_INSTALL_BIN} && \
./${JRE_INSTALL_BIN} && \
popd && \
{% elif files['linux-x64']['tar.gz'] %}
python2 downloader.py \
--url ${JRE_INSTALL_TAR_GZ_URL} \
--filename ${JRE_INSTALL_TAR_GZ} \
--username ${ORACLE_USERNAME} \
--password ${ORACLE_PASSWORD} && \
mkdir -p ${INSTALL_DIR} && \
tar -xzf ${JRE_INSTALL_TAR_GZ} --strip-components=1 -C ${INSTALL_DIR} && \
{%- endif %}
python2 downloader.py \
--url ${JCE_POLICY_ZIP_URL} \
--filename ${JCE_POLICY_ZIP} \
--username ${ORACLE_USERNAME} \
--password ${ORACLE_PASSWORD} && \
unzip -qq ${JCE_POLICY_ZIP} -d ${TEMP_DIR}/jce && \
find ${TEMP_DIR}/jce -name "*.jar" -print0 | xargs -0 mv -t ${INSTALL_DIR}/lib/security && \
popd && \
rm -rf ${TEMP_DIR_ROOT} && \
yum-install remove python-requests

ENV JAVA_HOME ${INSTALL_DIR}
ENV PATH ${JAVA_HOME}/bin:${JAVA_HOME}/jre/bin:${PATH}

USER ${APP_UID}
